package Tratamento;

public class BlocoTryCath {
    /*
        Sempre é utilizado quando no processo que será executado dentro de um método é esperado um erro, então cria-se um bloco "protegrido" onde qualqquer erro que ocorra do trecho "try" é direcionado para o trecho "cath" e sofrerá o devido tratamento de erro

    public static void main(String[] args) {
        try {
            PreparedStatement stmt = con.prepareStatement(query);
            //...
        } catch (SQLException e){
            throw new AcessoADadosException("Problema na criação de Statement", e);
        }
    }*/
}
